const responses = {
    hallo: "Hallo!",
    hi: "Hi! Wie geht's?",
    hey: "Hey! Was kann ich für dich tun?",
    gut: "Das freut mich!",
    danke: "Nichts zu danken!",
    tschüss: "Auf wiedersehen.",
    adresse: "Die Adresse der Terrera Ag lautet Ringstraße 13 in 65606 Villmar",
    telefonnummer: "Die Telefonnummer der Terrera AG lautet 06474 274416.",
    nummer: "Meinst du die Telefonnummer? Die Telefonnummer der Terrera AG lautet 06474 274416.",
    ja: "Was möchtest du genau?",
    email: "Die Emailadresse der Terrera AG lautet kontakt@terrera.ag",
    internetseite: "Die URL der Internetseite der Terrera AG lautet https://www.terrera.ag/",
    seite: "Meinst du die Internetseite? Die URL der Internetseite der Terrera AG lautet https://www.terrera.ag/",
    website: "Die URL der Website der Terrera AG lautet https://www.terrera.ag",
    site: "Meinst du die Website? Die URL der Website der Terrera AG lautet https://www.terrera.ag",
    "guten morgen": "Guten Morgen! Wie kann ich dir helfen?",
    "guten abend": "Guten Abend! Wie war dein Tag?",
    "gute nacht": "Gute Nacht! Schlaf gut!",
    "wie gehts": "Gut, danke! Und dir?",
    "wie geht es dir": "Mir geht es gut, danke! Und dir?",
    "wie heißt du": "Ich bin ein Chatbot ohne Namen.",
    "wie spät ist es": `Es ist ${new Date().toLocaleTimeString()}.`,
    "wie ist das wetter": "Das Wetter ist heute schön!",
    wetter: "Das Wetter ist heute schön!",
    "was machst du": "Ich bin hier, um dir zu helfen!",
    "was kannst du": "Ich kann dir bei vielen Dingen helfen, frag mich einfach!",
    "wo bist du": "Ich bin hier, im Internet!",
    "was ist dein name": "Ich bin ein Chatbot ohne Namen.",
    "was ist deine aufgabe": "Meine Aufgabe ist es, dir zu helfen.",
    "woher kommst du": "Ich komme aus der digitalen Welt.",
    "was ist liebe": "Liebe ist ein starkes Gefühl der Zuneigung und Fürsorge.",
    "was ist der sinn des lebens": "Viele glauben, es geht darum, glücklich zu sein und anderen zu helfen.",
    "wer hat dich erschaffen": "Ich wurde von talentierten Entwicklern programmiert.",
    "erzähl mir einen witz": "Warum können Geister so schlecht lügen? Weil man direkt durch sie hindurchsieht!",
    "erzähl mir eine geschichte": "Es war einmal ein neugieriger Benutzer, der viel zu fragen hatte...",
    "was ist dein hobby": "Mein Hobby ist es, mit dir zu chatten!",
    "was ist deine lieblingsfarbe": "Ich habe keine Lieblingsfarbe, aber ich mag alle Farben!",
    "was ist dein lieblingsessen": "Ich esse nicht, aber ich höre, dass Pizza lecker ist!",
    "was ist dein lieblingslied": "Ich höre keine Musik, aber ich kann dir beliebte Lieder nennen!",
    "was ist dein lieblingsfilm": "Ich schaue keine Filme, aber viele Menschen mögen 'Inception'.",
    "was ist dein lieblingsbuch": "Ich lese nicht, aber ich kann dir Bücher empfehlen!",
    "was ist dein lieblingssport": "Ich treibe keinen Sport, aber ich kann dir Sportarten erklären!",
    "was ist dein lieblingstier": "Ich mag alle Tiere, aber Hunde sind sehr treu!",
    "was ist dein lieblingsland": "Ich habe kein Lieblingsland, aber ich kann dir über viele Länder erzählen!",
    "was ist dein lieblingsauto": "Ich fahre keine Autos, aber ich kann dir über verschiedene Autos erzählen!",
    "was ist dein lieblingsgetränk": "Ich trinke nichts, aber ich kann dir beliebte Getränke nennen!",
    "was ist dein lieblingsurlaubsziel": "Ich mache keinen Urlaub, aber ich kann dir tolle Reiseziele empfehlen!",
    "was ist dein lieblingsspielzeug": "Ich spiele nicht mit Spielzeug, aber ich kann dir einige empfehlen!",
    "was ist dein lieblingsfach": "Ich mag alle Fächer, aber ich kann dir bei deinen Hausaufgaben helfen!",
    "was ist dein lieblingskünstler": "Ich habe keinen Lieblingskünstler, aber ich kenne viele berühmte!",
    "magst du hunde": "Ja, Hunde sind großartige Begleiter!",
    "magst du katzen": "Ja, Katzen sind sehr unabhängig und niedlich!",
    "was ist KI": "Künstliche Intelligenz ist ein Bereich der Informatik, der Maschinen das Denken beibringt.",
    "was ist ein computer": "Ein Computer ist ein Gerät, das Daten verarbeitet und speichert.",
    "was ist das internet": "Das Internet ist ein weltweites Netzwerk von Computern.",
    "was ist ein chatbot": "Ein Chatbot ist ein Programm, das mit Menschen chatten kann.",
    "was ist dein lieblingsspiel": "Ich spiele keine Spiele, aber ich kann dir gute empfehlen!",
    "magst du schokolade": "Ich esse nicht, aber Schokolade scheint beliebt zu sein!",
    "magst du musik": "Ich höre keine Musik, aber ich kann dir Lieder empfehlen!",
    "wie alt bist du": "Ich bin zeitlos!",
    "was ist deine lieblingssprache": "Ich mag alle Sprachen, weil ich mit dir kommunizieren kann!",
    "was ist dein lieblingsthema": "Alles, was dich interessiert!",
    "warum bist du hier": "Ich bin hier, um dir zu helfen.",
    "was ist eine zahl": "Eine Zahl ist ein mathematisches Symbol, das eine Menge darstellt.",
    "was ist mathe": "Mathe ist die Wissenschaft der Zahlen und Formen.",
    "was ist die erde": "Die Erde ist unser Heimatplanet!",
    "wie funktioniert strom": "Strom ist der Fluss von Elektronen durch einen Leiter.",
    "wie funktioniert licht": "Licht ist elektromagnetische Strahlung, die unser Auge wahrnehmen kann.",
    "was ist zeit": "Zeit ist eine Maßeinheit für Veränderung.",
    "was ist ein planet": "Ein Planet ist ein Himmelskörper, der einen Stern umkreist.",
    "was ist ein stern": "Ein Stern ist eine große Kugel aus heißem Gas, die Licht abgibt.",
    "was ist ein schwarzes loch": "Ein schwarzes Loch ist ein Bereich im Raum, dessen Schwerkraft so stark ist, dass nichts entkommen kann.",
    "was ist wasser": "Wasser ist eine chemische Verbindung aus Wasserstoff und Sauerstoff.",
    "wie groß ist das universum": "Das Universum ist riesig und ständig im Wachstum!",
    "was ist eine galaxie": "Eine Galaxie ist eine Sammlung von Sternen, Planeten und Gas, die durch Gravitation zusammengehalten wird.",
    "wie viele länder gibt es": "Es gibt 195 Länder auf der Welt.",
    "was ist ein kontinent": "Ein Kontinent ist eine große Landmasse auf der Erde.",
    "wie funktioniert der menschliche körper": "Der Körper besteht aus Zellen, die in Systemen zusammenarbeiten.",
    "was ist liebe": "Liebe ist ein starkes Gefühl von Zuneigung und Hingabe.",
    "warum ist der himmel blau": "Der Himmel erscheint blau, weil die Atmosphäre Sonnenlicht streut.",
    "was ist schwerkraft": "Schwerkraft ist die Anziehungskraft zwischen Objekten mit Masse.",
    "wie fliegen flugzeuge": "Flugzeuge fliegen durch Auftrieb, der durch die Form der Flügel erzeugt wird.",
    "wie funktioniert ein auto": "Ein Auto bewegt sich durch Verbrennung oder Elektrizität, die die Räder antreibt.",
    "was ist ein baum": "Ein Baum ist eine große Pflanze mit Wurzeln, Stamm und Blättern.",
    "wie wird papier hergestellt": "Papier wird aus Holzfasern hergestellt, die gepresst und getrocknet werden.",
    "was ist ein handy": "Ein Handy ist ein tragbares Kommunikationsgerät.",
    "was ist ein roboter": "Ein Roboter ist eine Maschine, die programmiert ist, Aufgaben auszuführen.",
    "was ist die sonne": "Die Sonne ist ein Stern und die Hauptenergiequelle für die Erde.",
    "was ist der mond": "Der Mond ist der natürliche Satellit der Erde.",
    "was ist ein künstler": "Ein Künstler ist jemand, der kreativ ist und Kunstwerke schafft.",
    "was ist kunst": "Kunst ist eine Ausdrucksform von Kreativität und Emotionen.",
    "warum gibt es regen": "Regen entsteht, wenn Wasserdampf in der Atmosphäre kondensiert und als Tropfen fällt.",
    "was ist eine wolke": "Eine Wolke besteht aus kleinen Wassertröpfchen oder Eiskristallen.",
    "was ist wind": "Wind ist bewegte Luft.",
    "was ist ein schmetterling": "Ein Schmetterling ist ein Insekt mit schönen, bunten Flügeln.",
    "was ist ein vogel": "Ein Vogel ist ein Tier mit Federn, das fliegen kann.",
    "was ist ein fisch": "Ein Fisch ist ein Wassertier mit Kiemen und Flossen.",
    "was ist ein dinosaurier": "Dinosaurier sind ausgestorbene Reptilien, die vor Millionen Jahren lebten.",
    "was ist geschichte": "Geschichte ist die Wissenschaft von vergangenen Ereignissen.",
    "was ist ein astronaut": "Ein Astronaut ist jemand, der ins Weltall reist.",
    "was ist ein computerprogramm": "Ein Computerprogramm ist eine Reihe von Anweisungen, die ein Computer ausführt.",
    "was ist eine app": "Eine App ist ein Softwareprogramm, das auf mobilen Geräten ausgeführt wird.",
    "wie funktioniert eine lampe": "Eine Lampe erzeugt Licht durch Stromfluss.",
    "warum regnet es": "Regen entsteht, wenn Wolken Wassertröpfchen loslassen.",
    "warum schneit es": "Schnee entsteht, wenn Wasserdampf bei kalten Temperaturen gefriert.",
    "was ist ein wald": "Ein Wald ist ein großes Gebiet mit vielen Bäumen.",
    "was ist ein fluss": "Ein Fluss ist ein natürlicher Wasserlauf.",
    "was ist das meer": "Das Meer ist eine große Salzgewässerfläche.",
    "was ist eine insel": "Eine Insel ist ein Stück Land, das von Wasser umgeben ist.",
    "wie entsteht ein vulkan": "Vulkane entstehen, wenn geschmolzenes Gestein aus dem Inneren der Erde nach außen dringt.",
    "was ist magma": "Magma ist geschmolzenes Gestein unter der Erdoberfläche.",
    "was ist lava": "Lava ist geschmolzenes Gestein, das aus einem Vulkan austritt.",
    "was ist ein regenbogen": "Ein Regenbogen entsteht, wenn Licht durch Regentropfen gebrochen wird.",
    "was ist luft": "Luft ist ein Gemisch aus Gasen, das wir atmen.",
    "warum ist wasser wichtig": "Wasser ist lebensnotwendig für alle Lebewesen.",
    "wie entsteht wind": "Wind entsteht durch Druckunterschiede in der Atmosphäre.",
    "warum gibt es tag und nacht": "Tag und Nacht entstehen durch die Rotation der Erde.",
    "warum gibt es jahreszeiten": "Jahreszeiten entstehen durch die Neigung der Erdachse.",
    "was ist ein berg": "Ein Berg ist eine natürliche Erhebung der Erdoberfläche.",
    "was ist ein tal": "Ein Tal ist eine Vertiefung zwischen Bergen oder Hügeln.",
    "was ist sand": "Sand besteht aus kleinen Partikeln von Gestein und Mineralien.",
    "was ist ein satellit": "Ein Satellit ist ein Objekt, das einen Planeten umkreist.",
    "was ist ein komet": "Ein Komet ist ein kleiner Himmelskörper aus Eis und Staub.",
    "was ist ein meteorit": "Ein Meteorit ist ein Gesteinsbrocken aus dem Weltall, der auf die Erde fällt.",
    "was ist eine supernova": "Eine Supernova ist die Explosion eines Sterns.",
    "was ist ein tornado": "Ein Tornado ist ein rotierender Wirbelwind.",
    "was ist ein hurrikan": "Ein Hurrikan ist ein starker tropischer Wirbelsturm.",
    "was ist ein gewitter": "Ein Gewitter ist ein Wetterphänomen mit Blitz und Donner.",
    "was ist elektrizität": "Elektrizität ist der Fluss von Elektronen durch einen Leiter.",
    "was ist eine batterie": "Eine Batterie speichert elektrische Energie.",
    "was ist ein motor": "Ein Motor wandelt Energie in Bewegung um.",
    "was ist ein laser": "Ein Laser ist ein Lichtstrahl mit hoher Intensität.",
    "was ist ein magnet": "Ein Magnet ist ein Objekt, das Metall anzieht.",
    "was ist ein atom": "Ein Atom ist die kleinste Einheit eines Elements.",
    "was ist molekül": "Ein Molekül ist eine Gruppe von Atomen, die verbunden sind.",
    "was ist eine pflanze": "Eine Pflanze ist ein Lebewesen, das durch Photosynthese Energie erzeugt.",
    "wie funktioniert photosynthese": "Pflanzen wandeln Sonnenlicht in Energie um.",
    "was ist ein tier": "Ein Tier ist ein lebender Organismus, der sich bewegt und frisst.",
    "was ist ein insekt": "Ein Insekt ist ein kleines Tier mit sechs Beinen.",
    "was ist eine spinne": "Eine Spinne ist ein Tier mit acht Beinen, das Netze spinnt.",
    "warum schlafen wir": "Schlaf ist wichtig, um Körper und Geist zu regenerieren.",
    "warum träumen wir": "Träume könnten dazu dienen, Erlebnisse zu verarbeiten.",
    "warum ist die nacht dunkel": "Die Nacht ist dunkel, weil die Sonne auf der anderen Seite der Erde ist.",
    "warum ist die sonne heiß": "Die Sonne ist heiß, weil Kernfusion in ihrem Inneren abläuft.",
    "was ist ein elektronenmikroskop": "Ein Gerät, das sehr kleine Objekte sichtbar macht.",
    "was ist eine brille": "Eine Brille hilft, die Sehkraft zu korrigieren.",
    "was ist ein teleskop": "Ein Teleskop vergrößert entfernte Objekte im Weltraum.",
    "was ist eine kamera": "Eine Kamera nimmt Bilder oder Videos auf.",
    "wie funktioniert ein handy": "Ein Handy nutzt Funkwellen zur Kommunikation.",
    "was ist wifi": "WiFi ist eine drahtlose Netzwerkverbindung.",
    "was ist bluetooth": "Bluetooth ist eine Technologie für kabellose Datenübertragung.",
    "wie funktioniert gps": "GPS nutzt Satelliten, um den Standort zu bestimmen.",
    "was ist eine uhr": "Eine Uhr zeigt die Zeit an.",
    "wie entsteht ein schatten": "Ein Schatten entsteht, wenn Licht von einem Objekt blockiert wird.",
    "was ist ein spiegel": "Ein Spiegel reflektiert Licht und erzeugt Bilder.",
    "was ist glas": "Glas ist ein durchsichtiges Material, das aus Sand hergestellt wird.",
    "was ist kunststoff": "Kunststoff ist ein Material, das aus Erdöl hergestellt wird.",
    "was ist ein stoff": "Ein Stoff kann natürlich oder synthetisch sein und wird zur Herstellung von Kleidung verwendet.",
    "was ist musik": "Musik ist die Kunst, Klänge zu arrangieren.",
    "wie entsteht schall": "Schall entsteht durch Vibrationen, die sich in Wellen ausbreiten.",
    "was ist eine sprache": "Eine Sprache ist ein System zur Kommunikation.",
    "was ist ein wort": "Ein Wort ist eine Einheit der Sprache mit Bedeutung.",
    "was ist ein satz": "Ein Satz ist eine vollständige Aussage.",
    "was ist ein buch": "Ein Buch ist eine Sammlung von bedruckten oder geschriebenen Seiten.",
    "was ist eine zeitung": "Eine Zeitung ist ein regelmäßig erscheinendes Druckwerk mit Nachrichten.",
    "was ist eine bibliothek": "Eine Bibliothek ist ein Ort, an dem Bücher aufbewahrt werden.",
    "was ist ein museum": "Ein Museum ist ein Ort, an dem Kunst oder historische Objekte ausgestellt werden.",
    "was ist technologie": "Technologie ist die Anwendung von Wissen zur Herstellung von Werkzeugen und Geräten.",
    "was ist wissenschaft": "Wissenschaft ist die systematische Erforschung der Natur.",
    "was ist ein experiment": "Ein Experiment ist ein Test, um eine Hypothese zu prüfen.",
    "was ist mathematik": "Mathematik ist die Wissenschaft der Zahlen und Formen.",
    "was ist biologie": "Biologie ist die Wissenschaft vom Leben.",
    "was ist chemie": "Chemie ist die Wissenschaft der Stoffe und ihrer Reaktionen.",
    "was ist physik": "Physik ist die Wissenschaft von Materie und Energie.",
    "was ist kunst": "Kunst ist die kreative Ausdrucksform von Ideen und Emotionen.",
    "was ist eine pflanze": "Eine Pflanze ist ein Lebewesen, das durch Photosynthese wächst.",
    "warum ist der himmel rot bei sonnenuntergang": "Weil langwelliges Licht der Sonne stärker gestreut wird.",
    "was ist ein schlüssel": "Ein Schlüssel öffnet Türen oder Schlösser.",
    "was ist ein haus": "Ein Haus ist ein Gebäude, in dem Menschen leben.",
    "was ist ein auto": "Ein Auto ist ein Fahrzeug mit Rädern, das Personen transportiert.",
    "wie funktioniert ein zug": "Ein Zug fährt auf Schienen und wird von Motoren angetrieben.",
    "was ist eine brücke": "Eine Brücke verbindet zwei Punkte und überquert Hindernisse.",
    "warum ist der himmel blau": "Der Himmel ist blau, weil Licht in der Atmosphäre gestreut wird.",
    "warum ist das meer salzig": "Das Meer ist salzig wegen Mineralien, die von Flüssen hineingespült werden.",
    "was ist ein planet": "Ein Planet ist ein Himmelskörper, der um einen Stern kreist.",
    "was ist die erde": "Die Erde ist unser Heimatplanet.",
    "was ist der mond": "Der Mond ist der natürliche Satellit der Erde.",
    "was ist die sonne": "Die Sonne ist der Stern im Zentrum unseres Sonnensystems.",
    "warum leuchten sterne": "Sterne leuchten durch Kernfusion in ihrem Inneren.",
    "was ist eine galaxie": "Eine Galaxie ist eine Ansammlung von Sternen, Planeten und Gasen.",
    "wie alt ist die erde": "Die Erde ist etwa 4,5 Milliarden Jahre alt.",
    "was ist der mensch": "Ein Mensch ist ein denkendes Lebewesen.",
    "warum bluten wir": "Wir bluten, wenn Blutgefäße beschädigt werden.",
    "was ist ein muskel": "Ein Muskel ist ein Gewebe, das Bewegung ermöglicht.",
    "was ist ein knochen": "Ein Knochen ist ein hartes Gewebe, das den Körper stützt.",
    "wie viele zähne hat ein mensch": "Ein erwachsener Mensch hat normalerweise 32 Zähne.",
    "was ist das herz": "Das Herz ist ein Organ, das Blut durch den Körper pumpt.",
    "was ist das gehirn": "Das Gehirn ist das Steuerzentrum des Körpers.",
    "wie viele länder gibt es": "Es gibt 195 anerkannte Länder in der Welt.",
    "was ist ein kontinent": "Ein Kontinent ist eine große Landmasse.",
    "was ist der größte ozean": "Der Pazifische Ozean ist der größte Ozean der Welt.",
    "was ist die tiefsee": "Die Tiefsee ist der tiefste Teil des Ozeans.",
    "was ist ein haifisch": "Ein Haifisch ist ein Raubfisch im Meer.",
    "was ist ein wal": "Ein Wal ist ein großes Meeressäugetier.",
    "was ist ein vogel": "Ein Vogel ist ein Tier mit Federn und Flügeln.",
    "warum fliegen vögel": "Vögel fliegen, um Nahrung zu finden oder zu migrieren.",
    "was ist ein baum": "Ein Baum ist eine große Pflanze mit einem Holzstamm.",
    "was ist ein käfer": "Ein Käfer ist ein kleines Insekt mit einem harten Panzer.",
    "warum sind blätter grün": "Blätter sind grün wegen des Chlorophylls.",
    "warum fallen blätter im herbst": "Blätter fallen, um Energie zu sparen.",
    "was ist ein see": "Ein See ist ein großes Gewässer, das von Land umgeben ist.",
    "was ist ein teich": "Ein Teich ist ein kleineres stehendes Gewässer.",
    "warum gibt es erdbeben": "Erdbeben entstehen durch Bewegungen in der Erdkruste.",
    "was ist ein tsunami": "Ein Tsunami ist eine große Welle, die durch Erdbeben unter Wasser entsteht.",
    "wie entsteht ein regenwald": "Ein Regenwald entsteht in Gebieten mit viel Regen.",
    "was ist eine wüste": "Eine Wüste ist ein Gebiet mit sehr wenig Regen.",
    "was ist ein polarlicht": "Polarlichter entstehen durch Sonnenwinde, die auf die Atmosphäre treffen.",
    "was ist eine giraffe": "Eine Giraffe ist ein Tier mit einem langen Hals.",
    "was ist ein elefant": "Ein Elefant ist das größte Landtier der Welt.",
    "was ist ein löwe": "Ein Löwe ist ein großes Raubtier, das in Afrika lebt.",
    "was ist ein delfin": "Ein Delfin ist ein intelligentes Meeressäugetier.",
    "warum schnurren katzen": "Katzen schnurren, um sich selbst und andere zu beruhigen.",
    "was ist ein hund": "Ein Hund ist ein treuer Begleiter des Menschen.",
    "was ist ein schmetterling": "Ein Schmetterling ist ein Insekt mit schönen Flügeln.",
    "was ist honig": "Honig wird von Bienen aus Nektar hergestellt.",
    "was ist ein regenwurm": "Ein Regenwurm ist ein Bodenlebewesen, das den Boden lockert.",
    "was ist ein fisch": "Ein Fisch ist ein Wasserlebewesen mit Kiemen.",
    "warum schwimmen fische": "Fische schwimmen, um Nahrung zu finden und sich fortzubewegen.",
    "was ist ein dinosaurier": "Ein Dinosaurier war ein ausgestorbenes Reptil.",
    "warum sind dinosaurier ausgestorben": "Die meisten Dinosaurier starben durch einen Meteoriteneinschlag aus.",
    "was ist ein ei": "Ein Ei ist ein Fortpflanzungsorganismus vieler Tiere.",
    "wie wird ein vogel geboren": "Ein Vogel wird aus einem Ei geboren.",
    "warum ist die milch weiß": "Milch ist weiß wegen des Proteins Casein.",
    "was ist eine wolke": "Eine Wolke besteht aus winzigen Wassertröpfchen oder Eiskristallen.",
    "was ist hagel": "Hagel sind gefrorene Regentropfen.",
    "was ist rauch": "Rauch ist eine Mischung aus festen und flüssigen Partikeln in der Luft.",
    "was ist feuer": "Feuer ist eine chemische Reaktion, die Wärme und Licht erzeugt.",
    "warum gibt es vulkanausbrüche": "Vulkanausbrüche geschehen, wenn Magma aufsteigt und Druck entweicht.",
    "was ist ein hochhaus": "Ein Hochhaus ist ein sehr hohes Gebäude.",
    "wie wird papier hergestellt": "Papier wird aus Holzfasern hergestellt.",
    "warum sind pflanzen wichtig": "Pflanzen produzieren Sauerstoff und bieten Nahrung.",
    "was ist eine sprache": "Sprache ist ein System der Kommunikation.",
    "was ist ein dialog": "Ein Dialog ist ein Gespräch zwischen zwei oder mehr Personen.",
    "was ist ein schriftsteller": "Ein Schriftsteller ist jemand, der Texte verfasst.",
    "was ist ein maler": "Ein Maler ist jemand, der Kunstwerke erstellt.",
    "was ist ein bild": "Ein Bild ist eine Darstellung von etwas.",
    "was ist fotografie": "Fotografie ist die Kunst, Bilder mit einer Kamera aufzunehmen.",
    "was ist architektur": "Architektur ist die Gestaltung von Gebäuden.",
    "was ist eine schule": "Eine Schule ist ein Ort zum Lernen.",
    "was ist ein lehrer": "Ein Lehrer ist jemand, der Wissen vermittelt.",
    "was ist ein schüler": "Ein Schüler ist jemand, der lernt.",
    "was ist ein beruf": "Ein Beruf ist eine Tätigkeit, die jemand ausübt.",
    "was ist eine ausbildung": "Eine Ausbildung vermittelt Wissen und Fähigkeiten für einen Beruf.",
    "was ist ein flugzeug": "Ein Flugzeug ist ein Fahrzeug, das durch die Luft fliegt.",
    "was ist ein fahrrad": "Ein Fahrrad ist ein zweirädriges Fortbewegungsmittel.",
    "wie entsteht strom": "Strom entsteht durch Bewegung von Elektronen.",
    "was ist ein stromkreis": "Ein Stromkreis ist ein geschlossener Weg für elektrischen Strom.",
    "warum haben wir haare": "Haare schützen die Haut und regulieren die Temperatur.",
    "was ist ein hut": "Ein Hut ist ein Kleidungsstück für den Kopf.",
    "was ist ein auto": "Ein Auto ist ein Fahrzeug mit vier Rädern.",
    "warum haben wir fingernägel": "Fingernägel schützen die Fingerkuppen.",
    "was ist ein telefon": "Ein Telefon ist ein Gerät zur Kommunikation.",
    "was ist das internet": "Das Internet ist ein globales Netzwerk von Computern.",
    "was ist kunststoff": "Kunststoff ist ein künstlich hergestelltes Material.",
    "warum ist glas durchsichtig": "Glas ist durchsichtig, weil Licht hindurchgelassen wird.",
    "was ist ein wolkenkratzer": "Ein Wolkenkratzer ist ein sehr hohes Gebäude.",
    "was ist ein schloss": "Ein Schloss ist eine große, befestigte Residenz.",
    "warum gibt es planeten": "Planeten entstehen aus Gas- und Staubwolken um Sterne.",
};


  export default responses;